#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="postgres"
prepare_service 10-postgres
check_container_initialized

case "${LOG_TYPE,,}" in
    file ) hide_output=silent ;;
esac

if [ "${SETUP_MODE,,}" = "auto" ] ; then
    engine_config="/etc/postgres/container.conf"
else
    engine_config="${CONFIG_PATH%/}/${CONFIG_FILE}"
fi

liftoff

print_start "Starting PostgreSQL $(psql --version | head -n 1 | awk '{print $NF}')"
TZ="${TIMEZONE}" ${hide_output} exec s6-setuidgid postgres postgres \
                                                                    --config_file="${engine_config}" ${SERVER_ARGS}
