#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service single
PROCESS_NAME="postgres"
output_off

bootstrap_filesystem
initialize_cluster
configure_server
control_server start
create_databases
configure_replication
configure_monitoring
control_server stop
print_info "PostgreSQL init process complete - ready for start up."
liftoff
