#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 10-postgres
SERVICE_NAME="postgres"
output_off

postgres_bootstrap_filesystem
postgres_initialize_cluster
postgres_configure_server
postgres_control_server start
postgres_create_databases
postgres_configure_replication
postgres_configure_monitoring
postgres_control_server stop
liftoff
