services:
  postgres-db:
    image: docker.io/nfrastack/postgres:17
    container_name: postgres-db
    volumes:
      - ./logs:/logs
      - ./db:/data
    environment:
      - TIMEZONE=America/Vancouver

      - SUPERUSER_PASS=superuser

      - DB_NAME=database
      - DB_USER=user
      - DB_PASS=password
    networks:
      - services
    restart: always

networks:
  services:
    external: false
