#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="postgres"
prepare_service
check_container_initialized

case "${LOG_TYPE,,}" in
    file ) hide_output=silent ;;
esac

liftoff

print_start "Starting PostgreSQL ${POSTGRES_VERSION}"
TZ="${TIMEZONE}" ${hide_output} exec s6-setuidgid postgres postgres \
                                    --config_file="${CONFIG_PATH}"/"${CONFIG_FILE}" ${SERVER_ARGS}
